---
kind: pipeline
type: docker
name: linux-amd64
platform:
  os: linux
  arch: amd64
steps:
  - name: ci
    image: rancher/dapper:v0.6.0
    environment:
      DRONE_TAG: ${DRONE_TAG}
      DRONE_COMMIT_SHA: ${DRONE_COMMIT_SHA}
    commands:
      - dapper ci
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - push
        - pull_request
        - tag
  - name: github_binary_release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      prerelease: false
      checksum:
        - sha256
      checksum_file: CHECKSUMsum-amd64.txt
      checksum_flatten: true
      files:
        - "bin/*"
      title: "${DRONE_TAG}"
    when:
      ref:
        include:
          - refs/tags/v*
        exclude:
          - refs/tags/*rc*
          - refs/tags/*alpha*
          - refs/tags/*beta*
      event:
        - tag
  - name: github_binary_prerelease
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      checksum:
        - sha256
      checksum_file: CHECKSUMsum-amd64.txt
      checksum_flatten: true
      files:
        - "bin/*"
      title: "Pre-release ${DRONE_TAG}"
    when:
      ref:
        include:
          - refs/tags/*rc*
          - refs/tags/*alpha*
          - refs/tags/*beta*
      event:
        - tag
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
node:
  instance: agent-amd64

---
kind: pipeline
name: linux-arm64
platform:
  os: linux
  arch: arm64
steps:
  - name: ci
    image: rancher/dapper:v0.6.0
    environment:
      DRONE_TAG: ${DRONE_TAG}
      DRONE_COMMIT_SHA: ${DRONE_COMMIT_SHA}
    commands:
      - dapper ci
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - push
        - pull_request
        - tag
  - name: github_binary_release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      prerelease: false
      checksum:
        - sha256
      checksum_file: CHECKSUMsum-arm64.txt
      checksum_flatten: true
      files:
        - "bin/*"
      title: "${DRONE_TAG}"
    when:
      ref:
        include:
          - refs/tags/v*
        exclude:
          - refs/tags/*rc*
          - refs/tags/*alpha*
          - refs/tags/*beta*
      event:
        - tag
  - name: github_binary_prerelease
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      checksum:
        - sha256
      checksum_file: CHECKSUMsum-arm64.txt
      checksum_flatten: true
      files:
        - "bin/*"
      title: "Pre-release ${DRONE_TAG}"
    when:
      ref:
        include:
          - refs/tags/*rc*
          - refs/tags/*alpha*
          - refs/tags/*beta*
      event:
        - tag
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
node:
  instance: agent-arm64
